import { useState } from 'react'
import { ArrowUpRight, CalendarDays, Check, ChevronRight, Menu, Phone, X } from 'lucide-react'
import './App.css'

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const closeMenu = () => setMenuOpen(false)

  return (
    <main>
      <header className="site-header"><a className="brand" href="#top" onClick={closeMenu}><span>AS</span> Orthopaedics</a><button className="menu-toggle" type="button" aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button><nav className={menuOpen ? 'nav-links open' : 'nav-links'}><a href="#about" onClick={closeMenu}>About</a><a href="#expertise" onClick={closeMenu}>Expertise</a><a href="#chambers" onClick={closeMenu}>Chambers</a><a className="nav-cta" href="#booking" onClick={closeMenu}>Book a visit <ArrowUpRight size={16} /></a></nav></header>
      <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Orthopaedic surgeon · Kolkata</p><h1>Movement is<br /><em>medicine.</em></h1><p className="hero-lede">Thoughtful, precise orthopaedic care for a life in motion.</p><a className="primary-button" href="#booking">Schedule a consultation <ArrowUpRight size={17} /></a><div className="hero-note"><span className="status-dot" /> Accepting new patients <span className="note-rule" /> <span>English · বাংলা · हिंदी</span></div></div><div className="hero-portrait"><div className="portrait-frame"><img src="https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=900&q=85" alt="Doctor in a white coat" /></div><div className="portrait-caption"><span>01</span><span>Care rooted in clarity</span></div><div className="seal">CARE<br /><span>with</span><br />INTENT</div></div></section>
      <section className="intro section-wrap" id="about"><div className="section-kicker"><span>01</span> The practice</div><div className="intro-content"><h2>A considered approach<br />to <em>better movement.</em></h2><div><p>Dr. Ayoon Sarker brings a calm, evidence-led approach to orthopaedic care. From a first assessment to recovery, every recommendation is made with your everyday life in mind.</p><a className="text-link" href="#expertise">Explore areas of expertise <ChevronRight size={16} /></a></div></div></section>
      <section className="expertise section-wrap" id="expertise"><div className="section-kicker"><span>02</span> Areas of expertise</div><div className="expertise-grid"><div className="expertise-image"><img src="https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=1000&q=85" alt="Orthopaedic consultation" /><span className="image-label">Precision in practice</span></div><div className="expertise-list"><p className="section-intro">Specialist guidance for the moments that ask more of your body.</p>{['Joint pain & arthritis', 'Sports & activity injuries', 'Fracture care', 'Rheumatology & inflammatory conditions'].map((item, index) => <div className="expertise-item" key={item}><span>0{index + 1}</span><h3>{item}</h3><ArrowUpRight size={18} /></div>)}</div></div></section>
      <section className="credentials section-wrap"><div className="section-kicker"><span>03</span> Credentials</div><div className="credentials-grid"><div><p className="big-number">15<span>+</span></p><p>years of clinical experience</p></div><div className="credential-block"><h3>Education</h3><p>MBBS<br />DNB Orthopaedics<br />Fellowship in Rheumatology, Pune</p></div><div className="credential-block"><h3>Experience</h3><p>Special Medical Officer, Orthopaedics<br />ESI Gourhati<br /><br />Registrar<br />Manipal Hospital Saltlake · Fortis Hospital Anandapur</p></div></div></section>
      <section className="chambers section-wrap" id="chambers"><div className="section-kicker light"><span>04</span> Chambers</div><div className="chambers-heading"><h2>Find care<br /><em>near you.</em></h2><p>Consultations are available at two convenient locations across Kolkata.</p></div><div className="chamber-grid"><article><span className="chamber-no">01</span><h3>Libberton<br />Orthopaedics Centre</h3><p>Kalikapur Road, Kolkata</p><a href="#booking">Get directions <ArrowUpRight size={15} /></a></article><article><span className="chamber-no">02</span><h3>Longlife<br />Speciality Clinic</h3><p>Mukundapur, Kolkata</p><a href="#booking">Get directions <ArrowUpRight size={15} /></a></article></div></section>
      <section className="booking section-wrap" id="booking"><div className="booking-copy"><div className="section-kicker"><span>05</span> Appointments</div><h2>Start your<br /><em>next chapter.</em></h2><p>Share a few details and our team will get back to you to confirm a suitable time.</p><div className="phone-line"><Phone size={17} /><div><small>Prefer to speak with us?</small><strong>Chamber contact number</strong></div></div></div><form className="booking-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }}>{submitted ? <div className="success"><div className="success-icon"><Check size={25} /></div><h3>Request received.</h3><p>Thank you. The chamber team will be in touch shortly to confirm your consultation.</p><button className="text-link" type="button" onClick={() => setSubmitted(false)}>Send another request <ChevronRight size={16} /></button></div> : <><label>Your name<input type="text" placeholder="Full name" required /></label><label>Phone number<input type="tel" placeholder="+91 00000 00000" required /></label><label>Preferred chamber<select defaultValue=""><option value="" disabled>Select a location</option><option>Libberton Orthopaedics Centre</option><option>Longlife Speciality Clinic</option></select></label><label>What can we help with?<textarea placeholder="A short note (optional)" rows="3" /></label><button className="primary-button" type="submit">Request an appointment <ArrowUpRight size={17} /></button><p className="form-note"><CalendarDays size={14} /> A team member will respond during clinic hours.</p></>}</form></section>
      <footer><a className="brand" href="#top"><span>AS</span> Orthopaedics</a><p>Specialist care for better movement.</p><a href="#top">Back to top ↑</a></footer>
    </main>
  )
}

export default App
